name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app
jobs:
  build:
    runs-on: macos-13-xl
    steps:
      - name: update swift
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - uses: actions/checkout@v3
      - name: Build macOS
        run: xcodebuild -scheme EasyMetalShader build -destination "generic/platform=macOS"
      - name: Build iOS
        run: xcodebuild -scheme EasyMetalShader build -destination "generic/platform=iOS"
  test:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v3
      - name: Test macOS
        run: xcodebuild -scheme EasyMetalShaderTests test -destination "platform=macOS,arch=x86_64"
      - name: Test iOS
        run: xcodebuild -scheme EasyMetalShaderTests test -destination "name=iPhone 14 Pro"
